import{a as p,S as b,i as l}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&s(y)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const L="https://pixabay.com/api/",w="44046646-50f8df335e976b654bc240f3a";async function m(e,r=1){const a=new URLSearchParams({key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15});try{const s=await p(L,{params:a});return{hits:s.data.hits,totalHits:s.data.totalHits}}catch(s){alert(s.message)}}function S(e){return`<li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
            <img class="gallery-image" width="360" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="captions">
            <li><strong>Likes</strong> ${e.likes}</li>
            <li><strong>Views</strong> ${e.views}</li>
            <li><strong>Comments</strong> ${e.comments}</li>
            <li><strong>Downloads</strong> ${e.downloads}</li>
            </ul>
            </li>
            `}function f(e){return e.map(S).join("")}const q=document.querySelector(".form"),c=document.querySelector(".gallery"),u=document.querySelector(".loader"),g=document.querySelector(".more-btn");let n="",d=1,i=0,h=new b(".gallery a",{captionsData:"alt"});q.addEventListener("submit",async e=>{if(e.preventDefault(),n=e.target.elements.query.value.trim(),!n){l.info({title:"Note",message:"Please enter your search"});return}c.innerHTML="",d=1,i=0,u.style.display="block";try{const r=await m(n,d);if(i=r.totalHits,r.hits.length===0)l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});else{const a=f(r.hits);c.innerHTML=a,h.refresh(),i>r.hits.length&&(g.style.display="block")}}catch(r){l.error({title:"Error",message:"Please try again later!"}),console.log(r)}finally{u.style.display="none"}});g.addEventListener("click",async()=>{d+=1,u.style.display="block";try{const e=await m(n,d),r=f(e.hits);c.insertAdjacentHTML("beforeend",r),h.refresh();const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"}),c.children.length>=i&&(g.style.display="none",l.info({title:"Note",message:"We're sorry, but you've reached the end of search results."}))}catch(e){l.error({title:"Error",message:"Please try again later!"}),console.log(e)}finally{u.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
